plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group   = 'com.labacacia'
version = '1.0.0-alpha.3'

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

repositories { mavenCentral() }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.xerial:sqlite-jdbc:3.47.1.0'
    implementation 'org.slf4j:slf4j-api'
}

springBoot { mainClass = 'com.labacacia.nipcaserver.NipCaApplication' }
